function fun3(X1)
%CREATEFIGURE(X1, Y1, Z1)
%  X1:  vector of x data
f = @(X1) 1./(2. + X1.*i);
t = -1:0.001:5;
g=@(t) exp(-2.*t).*(t>=0);
%  Auto-generated by MATLAB on 02-Apr-2019 01:14:23

figure1 = figure;
axes1 = axes('Parent',figure1);
hold(axes1,'on');
plot(t, g(t),'r','LineWidth',2);
title('Funcion en el tiempo f(t) = e^{-2t}')
xlabel('t')
ylabel('f(t)')
grid on
set(axes1,'XAxisLocation','origin','YAxisLocation','origin');

% Create figure
figure2 = figure;

% Create axes
axes2 = axes('Parent',figure2);
hold(axes2,'on');

% Create plot3
plot3(X1,real(f(X1)),imag(f(X1)),'LineWidth',2,...
    'Color',[0.749019622802734 0 0.749019622802734]);

% Create zlabel
zlabel('Im');

% Create ylabel
ylabel('Re');

% Create xlabel
xlabel('Frecuencia w');

% Create title
title('F(w) = 1/(2-jw)');

view(axes2,[-40.7 30.8]);
box(axes2,'on');
grid(axes2,'on');
% Set the remaining axes properties
set(axes2,'XAxisLocation','origin','YAxisLocation','origin');

figure3 = figure;
axes3 = axes('Parent',figure3);
hold(axes3,'on');
plot(X1, abs(f(X1)),'LineWidth',2,...
    'Color',[0.749019622802734 0 0.749019622802734]);
title('Espectro de magnitud')
xlabel('w')
ylabel('|(F(w)|')
grid on
set(axes3,'XAxisLocation','origin','YAxisLocation','origin');

figure4 = figure;
axes4 = axes('Parent',figure4);
hold(axes4,'on');
plot(X1, angle(f(X1)),'LineWidth',2,...
    'Color',[0.749019622802734 0 0.749019622802734]);
title('Espectro de fase')
xlabel('w')
ylabel('\angle (F(w)')
grid on
set(axes4,'XAxisLocation','origin','YAxisLocation','origin');
